local Games = {
    [3623096087] = "", -- Muscle Legends [ FLUENTUI ]
    [3101667897] = "", -- Legends Of Speed [ Coming Soon ]
    [126884695634066] = "", -- Grow A Garden [ Fixing ]
    [2753915549] = "", -- Blox Fruits [ LunarUI v2 ]
    [537413528] = "", -- Build a Boat For Treasure [ Featured ]
    [3956818381] = "", -- Ninja Legends 1 [ Featured ]
    [5977280685] = "", -- Ninja Legends 2 [ Featured ]
    [142823291] = "" -- Murder Mystery 2 [ Featured ]
}

return Games
