local Games = {
    [3623096087] = "https://raw.githubusercontent.com/Pxrson/Lunar-Hub/refs/heads/main/Main/Games/Files/Muscle%20Legends.luau", -- Muscle Legends [ FLUENTUI ]
    [3101667897] = "https://raw.githubusercontent.com/Pxrson/Lunar-Hub/refs/heads/main/Main/Games/Files/Legends%20Of%20Speed.luau", -- Legends Of Speed [ Coming Soon ]
    [126884695634066] = "https://raw.githubusercontent.com/Pxrson/Lunar-Hub/refs/heads/main/Main/Games/Files/Grow%20A%20Garden.luau", -- Grow A Garden [ Fixing ]
    [2753915549] = "https://raw.githubusercontent.com/Pxrson/Lunar-Hub/refs/heads/main/Main/Games/Files/Blox%20Fruits.luau", -- Blox Fruits [ LunarUI v2 ]
    [537413528] = "https://raw.githubusercontent.com/Pxrson/Lunar-Hub/refs/heads/main/Main/Games/Files/Build%20A%20Boat%20For%20Treasure.luau", -- Build a Boat For Treasure [ Featured ]
    [3956818381] = "https://raw.githubusercontent.com/Pxrson/Lunar-Hub/refs/heads/main/Main/Games/Files/Ninja%20Legends%201.luau", -- Ninja Legends 1 [ Featured ]
    [5977280685] = "https://raw.githubusercontent.com/Pxrson/Lunar-Hub/refs/heads/main/Main/Games/Files/Ninja%20Legends%202.luau", -- Ninja Legends 2 [ Featured ]
    [142823291] = "https://raw.githubusercontent.com/Pxrson/Lunar-Hub/refs/heads/main/Main/Games/Files/Murder%20Mystery%202.luau" -- Murder Mystery 2 [ Featured ]
}

return Games
